### ISSUE TITLE
IP Servidor GitHub Pages

### ISSUE THREAD

**Issue by mateussdev** [orige/githubpages.registro.br#1]
Olá amigo,

Recentemente eu criei uma pagina no github pages e tive que registrar o domínio pelo registro br. Achei seu tutorial e funcionou porém o github informou que o ip que você comenta no tutorial **204.232.175.78** não está sendo mas utilizado por eles.
Segue os ips que utilizei para configurar minha página.

* **192.30.252.153**
* **192.30.252.154**

[Aqui eles citam os ips acima.](https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/)

**Comment by orige** [comment]
@mateussdev , obrigado pelo lembrete. IPs atualizados.
